#######################################################
# Example Docker compose file for Falcon Services
#######################################################
version: '3'
services:
    backend:
      image: mohit24lkt/fitnessfuel:v2
      restart: always
      ports:
        - "3001:3001"
      depends_on: 
        - database
      environment: 
        - DATABASE_PORT=3306
        - DATABASE_HOST=database
        - DATABASE_USERNAME=root
        - DATABASE_PASSWORD=root
        - CORS_URL=http://localhost:81

    frontend:
      image: mohit24lkt/fitnessfuel-client:v2
      restart: always
      ports:
        - "81:80"
      environment: 
        - REACT_APP_BASE_URL=http://backend:3001
      
    database:
      image: mysql:8.0.23
      restart: always
      ports:
        - "3307:3306"
      environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=fitnessfuel
      volumes:
        - /var/lib/mysql:/var/lib/mysql
      